# Generated by Django 5.0.6 on 2025-09-20 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "units_block",
                "ordering": ["tower", "name"],
            },
        ),
        migrations.CreateModel(
            name="UnitTower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "units_tower",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código único de la unidad",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("departamento", "Departamento"),
                            ("cochera", "Cochera"),
                            ("bodega", "Bodega"),
                            ("estacionamiento", "Estacionamiento"),
                        ],
                        default="departamento",
                        max_length=20,
                    ),
                ),
                ("floor", models.IntegerField(blank=True, null=True)),
                ("number", models.CharField(blank=True, max_length=10)),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Área en m²",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "ownership_coefficient",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Coeficiente de copropiedad",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "bedrooms",
                    models.IntegerField(default=0, help_text="Número de habitaciones"),
                ),
                (
                    "bathrooms",
                    models.IntegerField(default=0, help_text="Número de baños"),
                ),
                (
                    "parking_spaces",
                    models.IntegerField(
                        default=0, help_text="Espacios de estacionamiento"
                    ),
                ),
                (
                    "storage_rooms",
                    models.IntegerField(default=0, help_text="Número de bodegas"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ocupada", "Ocupada"),
                            ("vacía", "Vacía"),
                            ("mantenimiento", "En Mantenimiento"),
                        ],
                        default="vacía",
                        max_length=20,
                    ),
                ),
                (
                    "owner_email",
                    models.EmailField(
                        blank=True, help_text="Email del propietario", max_length=254
                    ),
                ),
                (
                    "owner_phone",
                    models.CharField(
                        blank=True, help_text="Teléfono del propietario", max_length=20
                    ),
                ),
                (
                    "owner_whatsapp",
                    models.CharField(
                        blank=True, help_text="WhatsApp del propietario", max_length=20
                    ),
                ),
                (
                    "tenant_email",
                    models.EmailField(
                        blank=True, help_text="Email del inquilino", max_length=254
                    ),
                ),
                (
                    "tenant_phone",
                    models.CharField(
                        blank=True, help_text="Teléfono del inquilino", max_length=20
                    ),
                ),
                (
                    "tenant_whatsapp",
                    models.CharField(
                        blank=True, help_text="WhatsApp del inquilino", max_length=20
                    ),
                ),
                (
                    "owner_notifications",
                    models.BooleanField(
                        default=True, help_text="Propietario recibe notificaciones"
                    ),
                ),
                (
                    "tenant_notifications",
                    models.BooleanField(
                        default=True, help_text="Inquilino recibe notificaciones"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Propietario actual de la unidad",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Inquilino actual de la unidad",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rented_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="units.unitblock",
                    ),
                ),
            ],
            options={
                "db_table": "units_unit",
                "ordering": ["block__tower", "block", "code"],
            },
        ),
        migrations.CreateModel(
            name="UnitMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_in_unit",
                    models.CharField(
                        choices=[
                            ("propietario", "Propietario"),
                            ("inquilino", "Inquilino"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="units.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "units_membership",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="unitblock",
            name="tower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="units.unittower",
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["code"], name="units_unit_code_497400_idx"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["status"], name="units_unit_status_08f0cf_idx"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["owner"], name="units_unit_owner_i_94f23a_idx"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["tenant"], name="units_unit_tenant__ae26ee_idx"),
        ),
        migrations.AddIndex(
            model_name="unitmembership",
            index=models.Index(
                fields=["unit", "start_date"], name="units_membe_unit_id_73eaa4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unitmembership",
            index=models.Index(
                fields=["user", "start_date"], name="units_membe_user_id_3336de_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="unitblock",
            unique_together={("tower", "name")},
        ),
    ]
