# Generated by Django 5.0.6 on 2025-09-20 03:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("units", "0001_add_unit_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "amenity_type",
                    models.CharField(
                        choices=[
                            ("pool", "Piscina"),
                            ("gym", "Gimnasio"),
                            ("party_room", "Salón de Fiestas"),
                            ("bbq", "Parrillero"),
                            ("playground", "Parque Infantil"),
                            ("tennis", "Cancha de Tenis"),
                            ("basketball", "Cancha de Basketball"),
                            ("meeting_room", "Sala de Juntas"),
                            ("library", "Biblioteca"),
                            ("other", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("capacity", models.PositiveIntegerField()),
                ("location", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("advance_booking_days", models.PositiveIntegerField(default=7)),
                ("max_booking_hours", models.PositiveIntegerField(default=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "amenities_amenity",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AmenityBlackout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blackouts",
                        to="amenities.amenity",
                    ),
                ),
            ],
            options={
                "db_table": "amenities_amenityblackout",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="AmenityRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Por Hora"),
                            ("daily", "Por Día"),
                            ("fixed", "Tarifa Fija"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="amenities.amenity",
                    ),
                ),
            ],
            options={
                "db_table": "amenities_amenityrate",
                "ordering": ["amenity", "effective_date"],
            },
        ),
        migrations.CreateModel(
            name="AmenityReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("cancelled", "Cancelada"),
                            ("completed", "Completada"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("guests_count", models.PositiveIntegerField(default=1)),
                ("special_requirements", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="amenities.amenity",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_reservations",
                        to="units.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "amenities_amenityreservation",
                "ordering": ["-reservation_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="AmenityUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actual_start_time", models.DateTimeField(blank=True, null=True)),
                ("actual_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "actual_guests_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_in_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="amenities.amenityreservation",
                    ),
                ),
            ],
            options={
                "db_table": "amenities_amenityusage",
            },
        ),
        migrations.CreateModel(
            name="AmenitySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="amenities.amenity",
                    ),
                ),
            ],
            options={
                "db_table": "amenities_amenityschedule",
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {("amenity", "day_of_week", "start_time")},
            },
        ),
    ]
