# Generated by Django 5.0.6 on 2025-09-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="category",
            field=models.CharField(
                choices=[
                    ("electrical", "Eléctrico"),
                    ("plumbing", "Plomería"),
                    ("cleaning", "Limpieza"),
                    ("security", "Seguridad"),
                    ("maintenance", "Mantenimiento"),
                    ("construction", "Construcción"),
                    ("landscaping", "Jardinería"),
                    ("other", "Otro"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="services",
            field=models.TextField(blank=True),
        ),
    ]
