# Generated by Django 5.0.6 on 2025-09-20 00:51

import django.db.models.deletion
import notices.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("units", "0001_add_unit_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=notices.models.notice_image_upload_path,
                    ),
                ),
                (
                    "audience_scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("torre", "Torre"),
                            ("bloque", "Bloque"),
                            ("unidad", "Unidad"),
                            ("propietarios", "Propietarios"),
                            ("inquilinos", "Inquilinos"),
                        ],
                        default="global",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "publish_at",
                    models.DateTimeField(help_text="Fecha y hora de publicación"),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, help_text="Fecha y hora de expiración", null=True
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Archivo adjunto (PDF, imagen, etc.)",
                        null=True,
                        upload_to="notices/attachments/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requires_confirmation",
                    models.BooleanField(
                        default=False, help_text="Requiere confirmación de lectura"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_block",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bloque objetivo (si scope es bloque o unidad)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="units.unitblock",
                    ),
                ),
                (
                    "target_tower",
                    models.ForeignKey(
                        blank=True,
                        help_text="Torre objetivo (si scope es torre, bloque o unidad)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="units.unittower",
                    ),
                ),
                (
                    "target_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Unidad objetivo (si scope es unidad)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="units.unit",
                    ),
                ),
            ],
            options={
                "db_table": "notices_notice",
                "ordering": ["-publish_at", "-priority"],
            },
        ),
        migrations.CreateModel(
            name="NoticeReadConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_confirmations",
                        to="notices.notice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notices_noticereadconfirmation",
                "ordering": ["-read_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["audience_scope"], name="notices_not_audienc_4fa43c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["publish_at"], name="notices_not_publish_0db594_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["expire_at"], name="notices_not_expire__ff7677_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["priority"], name="notices_not_priorit_da59d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["requires_confirmation"], name="notices_not_require_538ea7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="noticereadconfirmation",
            index=models.Index(
                fields=["notice", "user"], name="notices_not_notice__1acfaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="noticereadconfirmation",
            index=models.Index(
                fields=["read_at"], name="notices_not_read_at_3e33a7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="noticereadconfirmation",
            unique_together={("notice", "user")},
        ),
    ]
