# Generated by Django 5.0.6 on 2025-09-20 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("units", "0001_add_unit_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("due_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False, help_text="Período cerrado para facturación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "finance_billingperiod",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["start_date"], name="finance_bil_start_d_a93eae_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="finance_bil_end_dat_b63c52_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="finance_bil_due_dat_305fdf_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="finance_bil_is_acti_914ec9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeeConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "concept_type",
                    models.CharField(
                        choices=[
                            ("expensa_ordinaria", "Expensa Ordinaria"),
                            ("expensa_extraordinaria", "Expensa Extraordinaria"),
                            ("multa", "Multa"),
                            ("interes", "Interés"),
                            ("otros", "Otros"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("por_coeficiente", "Por Coeficiente de Copropiedad"),
                            ("fijo", "Monto Fijo"),
                            ("mixto", "Mixto (Fijo + Coeficiente)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monto base para cálculos fijos o mixtos",
                        max_digits=10,
                    ),
                ),
                (
                    "coefficient_multiplier",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="Multiplicador para cálculos por coeficiente",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=True, help_text="Es un cargo recurrente"
                    ),
                ),
                (
                    "billing_day",
                    models.IntegerField(
                        default=1, help_text="Día del mes para facturación (1-31)"
                    ),
                ),
                (
                    "has_penalty",
                    models.BooleanField(
                        default=False, help_text="Tiene penalización por mora"
                    ),
                ),
                (
                    "penalty_days",
                    models.IntegerField(
                        default=5,
                        help_text="Días de gracia antes de aplicar penalización",
                    ),
                ),
                (
                    "penalty_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje de penalización por mora",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "finance_feefconcept",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["concept_type"], name="finance_fee_concept_8d70b9_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="finance_fee_is_acti_27895f_idx"
                    ),
                    models.Index(
                        fields=["is_recurring"], name="finance_fee_is_recu_6a2410_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UnitCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagado", "Pagado"),
                            ("vencido", "Vencido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "penalty_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("penalty_applied_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="finance.billingperiod",
                    ),
                ),
                (
                    "fee_concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="finance.feeconcept",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="units.unit",
                    ),
                ),
            ],
            options={
                "db_table": "finance_unitcharge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("transferencia", "Transferencia"),
                            ("cheque", "Cheque"),
                            ("tarjeta", "Tarjeta"),
                            ("otros", "Otros"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Número de referencia o comprobante",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit_charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="finance.unitcharge",
                    ),
                ),
            ],
            options={
                "db_table": "finance_payment",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.AddIndex(
            model_name="unitcharge",
            index=models.Index(
                fields=["unit", "status"], name="finance_uni_unit_id_d48cc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unitcharge",
            index=models.Index(
                fields=["due_date"], name="finance_uni_due_dat_dad764_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unitcharge",
            index=models.Index(fields=["status"], name="finance_uni_status_7e29c3_idx"),
        ),
        migrations.AddIndex(
            model_name="unitcharge",
            index=models.Index(
                fields=["billing_period"], name="finance_uni_billing_867916_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="unitcharge",
            unique_together={("unit", "fee_concept", "billing_period")},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date"], name="finance_pay_payment_72f761_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_method"], name="finance_pay_payment_0f610f_idx"
            ),
        ),
    ]
