# Generated by Django 5.0.6 on 2025-09-20 03:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_add_finance_models"),
        ("units", "0001_add_unit_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_creditnote",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Fine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fine_type",
                    models.CharField(
                        choices=[
                            ("noise", "Ruido"),
                            ("parking", "Estacionamiento"),
                            ("common_area", "Área Común"),
                            ("pets", "Mascotas"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("fine_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("partial", "Parcialmente Pagado"),
                            ("paid", "Pagado"),
                            ("overdue", "Vencido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_fine",
                "ordering": ["-fine_date"],
            },
        ),
        migrations.CreateModel(
            name="InterestRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "calculation_base",
                    models.CharField(
                        choices=[("daily", "Diario"), ("monthly", "Mensual")],
                        max_length=20,
                    ),
                ),
                (
                    "max_interest",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("effective_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_interestrate",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.RemoveIndex(
            model_name="billingperiod",
            name="finance_bil_start_d_a93eae_idx",
        ),
        migrations.RemoveIndex(
            model_name="billingperiod",
            name="finance_bil_end_dat_b63c52_idx",
        ),
        migrations.RemoveIndex(
            model_name="billingperiod",
            name="finance_bil_due_dat_305fdf_idx",
        ),
        migrations.RemoveIndex(
            model_name="billingperiod",
            name="finance_bil_is_acti_914ec9_idx",
        ),
        migrations.RemoveIndex(
            model_name="feeconcept",
            name="finance_fee_concept_8d70b9_idx",
        ),
        migrations.RemoveIndex(
            model_name="feeconcept",
            name="finance_fee_is_acti_27895f_idx",
        ),
        migrations.RemoveIndex(
            model_name="feeconcept",
            name="finance_fee_is_recu_6a2410_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="finance_pay_payment_72f761_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="finance_pay_payment_0f610f_idx",
        ),
        migrations.RemoveIndex(
            model_name="unitcharge",
            name="finance_uni_unit_id_d48cc9_idx",
        ),
        migrations.RemoveIndex(
            model_name="unitcharge",
            name="finance_uni_due_dat_dad764_idx",
        ),
        migrations.RemoveIndex(
            model_name="unitcharge",
            name="finance_uni_status_7e29c3_idx",
        ),
        migrations.RemoveIndex(
            model_name="unitcharge",
            name="finance_uni_billing_867916_idx",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="unit_charge",
            new_name="charge",
        ),
        migrations.RenameField(
            model_name="unitcharge",
            old_name="penalty_amount",
            new_name="discount_amount",
        ),
        migrations.RenameField(
            model_name="unitcharge",
            old_name="description",
            new_name="notes",
        ),
        migrations.RemoveField(
            model_name="billingperiod",
            name="description",
        ),
        migrations.RemoveField(
            model_name="billingperiod",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="feeconcept",
            name="billing_day",
        ),
        migrations.RemoveField(
            model_name="feeconcept",
            name="has_penalty",
        ),
        migrations.RemoveField(
            model_name="feeconcept",
            name="is_recurring",
        ),
        migrations.RemoveField(
            model_name="feeconcept",
            name="penalty_days",
        ),
        migrations.RemoveField(
            model_name="feeconcept",
            name="penalty_rate",
        ),
        migrations.RemoveField(
            model_name="unitcharge",
            name="paid_date",
        ),
        migrations.RemoveField(
            model_name="unitcharge",
            name="penalty_applied_date",
        ),
        migrations.AddField(
            model_name="feeconcept",
            name="requires_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="payments/"),
        ),
        migrations.AddField(
            model_name="unitcharge",
            name="interest_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="unitcharge",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="billingperiod",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="feeconcept",
            name="base_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="feeconcept",
            name="calculation_type",
            field=models.CharField(
                choices=[
                    ("coefficient", "Por Coeficiente"),
                    ("fixed", "Monto Fijo"),
                    ("mixed", "Mixto"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feeconcept",
            name="coefficient_multiplier",
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="feeconcept",
            name="concept_type",
            field=models.CharField(
                choices=[
                    ("ordinary", "Gasto Ordinario"),
                    ("extraordinary", "Gasto Extraordinario"),
                    ("fine", "Multa"),
                    ("interest", "Interés Moratorio"),
                    ("other", "Otro"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feeconcept",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Efectivo"),
                    ("transfer", "Transferencia"),
                    ("deposit", "Depósito"),
                    ("qr", "QR"),
                    ("check", "Cheque"),
                    ("other", "Otro"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="unitcharge",
            name="billing_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finance.billingperiod"
            ),
        ),
        migrations.AlterField(
            model_name="unitcharge",
            name="fee_concept",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finance.feeconcept"
            ),
        ),
        migrations.AlterField(
            model_name="unitcharge",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("partial", "Parcialmente Pagado"),
                    ("paid", "Pagado"),
                    ("overdue", "Vencido"),
                    ("cancelled", "Cancelado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="feeconcept",
            table="finance_feeconcept",
        ),
        migrations.AddField(
            model_name="creditnote",
            name="approved_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_credits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="charge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_notes",
                to="finance.unitcharge",
            ),
        ),
        migrations.AddField(
            model_name="fine",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="fine",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fines",
                to="units.unit",
            ),
        ),
    ]
