# Generated by Django 5.0.6 on 2025-09-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_creditnote_fine_interestrate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingperiod",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Efectivo"),
                    ("bank_transfer", "Transferencia Bancaria"),
                    ("check", "Cheque"),
                    ("credit_card", "Tarjeta de Crédito"),
                    ("other", "Otro"),
                ],
                max_length=20,
            ),
        ),
    ]
