# Generated by Django 5.0.6 on 2025-09-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="document_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
