# Generated by Django 5.0.6 on 2025-09-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_alter_visitor_document_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="photo",
            field=models.FileField(blank=True, null=True, upload_to="visitors/"),
        ),
    ]
