# Generated by Django 5.0.6 on 2025-09-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0003_alter_visitor_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessauthorization",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
