# Generated by Django 5.0.6 on 2025-09-25 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0004_alter_accessauthorization_end_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[("entry", "Entrada"), ("exit", "Salida")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Puntuación de confianza del reconocimiento"
                    ),
                ),
                ("camera_location", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="security.visitor",
                    ),
                ),
            ],
            options={
                "db_table": "security_visitor_attendance",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="VisitorFaceEncoding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "face_encoding",
                    models.TextField(help_text="Codificación facial en formato JSON"),
                ),
                (
                    "confidence_threshold",
                    models.FloatField(
                        default=0.6, help_text="Umbral de confianza para reconocimiento"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visitor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_encoding",
                        to="security.visitor",
                    ),
                ),
            ],
            options={
                "db_table": "security_visitor_face_encoding",
            },
        ),
    ]
